### PR TITLE
Included schema should inherit target namespace

### LINKED ISSUE #113: Included schema should inherit targetNamespace from parent
I have a quite complex schema at hand, that is split up into multiple files. There are some enums defined in one of the included files. It fails with unknown type in variantbuilder, and as far as i could nail it down, it is because of when state.get_node is getting called, the included schema is not resolved (or respected in the search, I still did not dive into the resolve mechanism).

at the time when get_node is invoked the schema looks like:

Image

so i understand that the type from the included file cannot be found.

What would be a good way to make this work?

[ONIX_BookProduct_3.1_test.xsd.txt](https://github.com/user-attachments/files/21484891/ONIX_BookProduct_3.1_test.xsd.txt)

[ONIX_BookProduct_CodeLists_test.xsd.txt](https://github.com/user-attachments/files/21484892/ONIX_BookProduct_CodeLists_test.xsd.txt)

Those files reproduce the error. Had to rename them to .txt otherwise github did not allow the upload.

### PR DESCRIPTION
**Pull request by eiswind**
resolves #113.

Please take a look. I'll be on a rainy road trip until sunday, so no hurry.

### CODE REVIEW

File: src/pipeline/parser/resolver/mod.rs [hunk 1]
```diff
@@ -60,6 +60,18 @@ pub struct ResolveRequest {
...
     /// Namespace of the current processed schema.
     pub current_ns: Option<Namespace>,
+
+    /// Import or Include
+    pub request_type: Option<ResolveRequestType>,
+}
+
+/// Distinction of included vs imported schemas
+#[derive(Debug)]
+pub enum ResolveRequestType {
```
Comment (Bergmann89) [inline src/pipeline/parser/resolver/mod.rs:70]: I would like to add then `None` case of the `Option<ResolveRequestType>` directly to the enum. This makes it easier to compare.

```rust
#[derive(Default, Debug, Clone, Copy, Eq, PartialEq)]
pub enum ResolveRequestType {
    /// Schema was added directly by the user
    #[default]
    UserDefined,
    
    /// Schema has been included
    IncludeRequest,
    
    /// Schema has been imported
    ImportRequest,
}
```

**Review by Bergmann89 — CHANGES_REQUESTED** [review]
Looks good :+1: Just two small notes:

- It's cleaner to merge the `None` of the `Option<ResolveRequestType>` directly to the enum (see comment)
- Can you please squash all your changes to one single commit? And please also remove the link to the issue and give a short description why this change was needed. I would like to keep the git history more or less free from extra tools and put the relevant information directly into the commit message.

Have a nice trip :slightly_smiling_face:

File: src/pipeline/parser/mod.rs [hunk 2]
```diff
@@ -417,6 +425,8 @@ fn import_req(
 
     let mut req = ResolveRequest::new(location);
 
+    req = req.request_type(ResolveRequestType::ImportRequest);
```
[the remark this answers is not in the document]
Comment (Bergmann89) [reply src/pipeline/parser/mod.rs:428]: @eiswind Yes, that's a good idea. Go for it :)

File: src/pipeline/parser/mod.rs [hunk 3]
```diff
@@ -298,7 +299,14 @@ where
         let reader = SchemaReader::new(reader);
         let mut reader = reader.with_error_info();
 
-        let schema = Schema::deserialize(&mut reader)?;
+        let mut schema = Schema::deserialize(&mut reader)?;
+
+        if ResolveRequestType::IncludeRequest == req.request_type {
+            if let Some(current_ns) = req.current_ns {
+                let inherited_ns = current_ns.to_string();
+                schema.target_namespace = Some(inherited_ns);
```
Comment (Bergmann89) [inline src/pipeline/parser/mod.rs:307]: I think we should only set the namespace if it is not already set:

```rust
        if schema.target_namespace.is_none() && ResolveRequestType::IncludeRequest == req.request_type {
            if let Some(current_ns) = req.current_ns {
                let inherited_ns = current_ns.to_string();
                schema.target_namespace = Some(inherited_ns);
            }
        }
```

Comment (eiswind) [reply src/pipeline/parser/mod.rs:309]: Good idea!

**Review by Bergmann89 — APPROVED** [review]
Looks good. Approved :+1:  But the checks are failing :worried:

**Comment by eiswind** [comment]
Looks like running 'cargo clippy' was not enough ;) I'll check that.

**Review by Bergmann89 — APPROVED** [review]
